package controller;

public enum Events {
    EXTEND, SHOW_HOME, SHOW_ELECTRODOMESTICS, ENABLE_ECO,
    DISABLE_ECO, SING_OUT, CONTRACT,
    SHOW_SING_IN, SHOW_SING_UP, SING_UP, SING_IN,
    END_SING_IN, POWER_ON, POWER_OFF, DISCONNECT
}
